### ISSUE TITLE
IPFS data spec update:  bounty_network

### ISSUE THREAD

**Issue by owocki** [ConsenSys/StandardBounties#20]
lets add a `bounty_network` param to the IPFS JSON sample so that networks can self identify as `bounties_factory` or `gitcoin`

https://github.com/gitcoinco/web/commit/4c985f137c81515f52a1e7c8a1bf5a1641930981

**Comment by mbeylin** [comment]
being discussed here https://github.com/ConsenSys/StandardBounties/issues/21
