### ISSUE TITLE
IPFS data spec update: schema_name and schema_version

### ISSUE THREAD

**Issue by owocki** [ConsenSys/StandardBounties#21]
# what

I suggest adding two new fields to the IPFS JSON for bounties.network:

* schema_name: the name of the schema that is being used. (example: `bounties_network`, `gitcoin` )
* schema_version: the version of the schema that is being used (ex: 0.1, 0.11, 1.0) 

# why

formalizing these two fields would recognize the business case reality that different bounty networks are likely to have different use cases and thereby, different metadata they need to store about the bounties.  

by recognizing this implicit fact explicitly, different implementers of the bounties network:

1. can have different JSON metadata formats (instead of trying to all work around one format).  
2. could formalize their JSON formats explicitly, allowing more easy management of said formats.
3. can manage the versioning of their formats as their business needs evolve.
4. ingestion of bounties across networks becomes easier because there is documentation of each networks presumed metadata.

# suggested next steps

1. accept schema_name / schema_version as standard parts of the IPFS json
2. publish samples of both the bounties_factory and gitcoin formats to this repo
3. define and publish documentation on required fields for each schema (title, description, sourceFileHash, etc). 
4. maintain those specifications over time as our business needs evolve.

**Comment by jasonrhaas** [comment]
We probably need a sub schema name as well.  For example, there is the `gitcoin_bounty`, and the `gitcoin_fulfillment`.  This is what I'm adding to the Gitcoin code as we speak:

```
        var ipfsBounty = {
            // StandardBounties Fields
            title: metadata.issueTitle,
            description: metadata.issueDescription,
            sourceFileHash: "",
            sourceFileName: "",
            contact: metadata.notificationEmail,
            categories: metadata.issueKeywords.split(","),
            githubLink: issueURL,
            // Additional fields added for gitcoin
            web3created: new Date().getTime()/1000|0,
            tokenName : tokenName,
            tokenAddress: tokenAddress,
            metadata: metadata,
            // Schema info
            // See https://github.com/ConsenSys/StandardBounties/issues/21
            schemaName: 'gitcoin_bounty',
            schemaVersion: '0.1',
        };
```
```
            var ipfsFulfill = {
                // StandardBounties Fields
                description: issueURL,
                sourceFileName: "",
                sourceFileHash: "",
                sourceDirectoryHash: "",
                contact: notificationEmail,
                // Additional fields added for gitcoin
                fulfillerAddress: account,
                fulfillerMetadata: fulfillerMetadata,
                schemaName: 'gitcoin_fulfillment',
                schemaVersion: '0.1'
            }
```

**Comment by owocki** [comment]
seems like we’re overloading the first layer of the JS for this

how much pain would it incur to move to something like this

from the consensys chat

```
ipfsBounty = {
    // StandardBounties Fields
    // Schema info
    // See https://github.com/ConsenSys/StandardBounties/issues/21
    meta: {
        sourceFileHash: "",
        sourceFileName: "",
        schemaName: 'gitcoinBounty',
        schemaVersion: '0.1',
    }
    payload: {
        // -- required fields for StandardBounty
        title: metadata.issueTitle,
        description: metadata.issueDescription,
        tokenName : tokenName,
        tokenAddress: tokenAddress,
        // -- Additional fields added for gitcoin
        contact_email: metadata.notificationEmail,
        githubLink: issueURL,
        created: new Date().getTime()/1000|0,
        categories: metadata.issueKeywords.split(","),
    },
};
```

**Comment by jasonrhaas** [comment]
Its not a big deal either way -- just need to update the backend to match up with the new schema.

**Comment by mbeylin** [comment]
How about:

```
{
  payload: {
    title: // A string representing the title of the bounty
    description: // A string representing the description of the bounty, including all requirements
    sourceFileName: // A string representing the name of the file
    sourceFileHash: // The IPFS hash of the file associated with the bounty
    contactEmail: // A string representing the preferred contact method of the issuer of the bounty
    categories: // an array of strings, representing the categories of tasks which are being requested
    githubLink: // The link to the relevant repository
    created: // the timestamp in seconds when the bounty was created
  }
  meta: {
    platform: // a string representing the original posting platform (ie 'gitcoin')
    schemaVersion: // a string representing the version number (ie '0.1')
  }
}
```
this preserves the camel casing that's there, and makes sure the different fields are in the right sections (sourceFileName and sourceFileHash are definitely both payload type fields)

**Comment by owocki** [comment]
@mbeylin can we add a 'schemaName' to the 'meta' dict?

**Comment by owocki** [comment]
@mbeylin the other thing i think your version of the schema is missing is the seperation of optional / required fields in the `payload` area

**Comment by mbeylin** [comment]
Couldn't optional fields just be added on to the payload as platforms desire?

Also I believe `platform` replaces the need for `schemaName` (and also schema name is confusing because in theory we should all be using the same schema)

**Comment by owocki** [comment]
>Also I believe platform replaces the need for schemaName (and also schema name is confusing because in theory we should all be using the same schema)

`platform` isnt the same as `schemaName`.. more than one platform can be on the same schema name.  might as well future-proof now

> Couldn't optional fields just be added on to the payload as platforms desire?

i think that we should have optional fields 

1. commented in such a way that it's explicit which ones they are (e.g. http://bits.owocki.com/212d0l2D111Y/Screen%20Shot%202018-01-19%20at%202.21.11%20PM.png )
2. merged into the upstream spec so that different platforms can coallesce on using them in the same way.  (for example `github_url` vs `githubLink` vs `githubLink` -- i'd want bounties.network and gitcoin and status open bounty (or whatever) to be able to coordinate their usage instead of making up undocumented one-offs)

**Comment by mbeylin** [comment]
That all looks good to me. I actually added the gitcoin schema fields into the main one as well (converting `contact` into `contactEmail`, and adding the `created` field). How's this: 

{
  payload: {
    title: // A string representing the title of the bounty
    description: // A string representing the description of the bounty, including all requirements
    sourceFileName: // A string representing the name of the file
    sourceFileHash: // The IPFS hash of the file associated with the bounty
    sourceDirectoryHash: // The IPFS hash of the directory which can be used to access the file
    contactEmail: // A string representing the preferred contact method of the issuer of the bounty
    categories: // an array of strings, representing the categories of tasks which are being requested
    githubLink: // The link to the relevant repository
    created: // the timestamp in seconds when the bounty was created
    // ------- add optional fields here -------
  }
  meta: {
    platform: // a string representing the original posting platform (ie 'gitcoin')
    schemaVersion: // a string representing the version number (ie '0.1')
    schemaName: // a string representing the name of the schema (ie 'standardSchema' or 'gitcoinSchema') 
  }
}

**Comment by owocki** [comment]
i propose one edit (moving some of the optional fields around).  also changes `githubLink` to `webLink` and some of the `contact*` info

```
{
  payload: {
    title: // A string representing the title of the bounty
    description: // A string representing the description of the bounty, including all requirements
    sourceFileName: // A string representing the name of the file
    sourceFileHash: // The IPFS hash of the file associated with the bounty
    sourceDirectoryHash: // The IPFS hash of the directory which can be used to access the file
    created: // the timestamp in seconds when the bounty was created
    webLink: // The link to the web resource for this
    // ------- add optional fields here -------
    categories: // an array of strings, representing the categories of tasks which are being requested
    funderEmail: // A string representing the preferred contact method of the issuer of the bounty
    funderGithubUsername: // A string representing the github username of the funder
    fulfillerEmail: // A string representing the preferred contact method of the issuer of the bounty
    fulfillerGithubUsername: // A string representing the github username of the funder

  }
  meta: {
    platform: // a string representing the original posting platform (ie 'gitcoin')
    schemaVersion: // a string representing the version number (ie '0.1')
    schemaName: // a string representing the name of the schema (ie 'standardSchema' or 'gitcoinSchema') 
  }
}
```

**Comment by mbeylin** [comment]
A couple notes:
- why can't categories be mandatory! I think those are pretty standard to have across platforms, even if the categories themselves change
- what would the difference be between `funderEmail` and `contactEmail` (beyond nomenclature)?
- how would the issuer of a bounty ever know the eventual fulfiller's email and github username? Wouldn't those go into the `data` schema for bounty fulfillments?

I would suggest that schema to be:
```
{
  payload: {
    description: // A string representing the description of the fulfillment, and any necessary links to works
    sourceFileName: // A string representing the name of the file being submitted
    sourceFileHash: // A string representing the IPFS hash of the file being submitted
    sourceDirectoryHash: // A string representing the IPFS hash of the directory which holds the file being submitted
    contactEmail: // A string representing the preferred contact method of the fulfiller of the bounty
    // ------- add optional fields here -------
    fulfillerGithubUsername: // A string representing the github username of the funder
  },
  meta: {
    platform: // a string representing the original posting platform (ie 'gitcoin')
    schemaVersion: // a string representing the version number (ie '0.1')
    schemaName: // a string representing the name of the schema (ie 'standardSchema' or 'gitcoinSchema')
  }
}
```
This includes the `fulfillerGithubUsername` field, and lets the `fulfillerEmail` just be the `contactEmail`

**Comment by owocki** [comment]
> why can't categories be mandatory! I think those are pretty standard to have across platforms, even if the categories themselves change

ok, you are right.

> what would the difference be between funderEmail and contactEmail (beyond nomenclature)?

more specificity == better

> how would the issuer of a bounty ever know the eventual fulfiller's email and github username? Wouldn't those go into the data schema for bounty fulfillments?

ANOTHER SCHEMA we need to figure out!?? i guess i wasnt close enough to this to know that there were multiple json schemas to keep updated..   why not just update the same data file and have a `issuerPayload` and a `fulfillerPayload` ?

**Comment by mbeylin** [comment]
The `data` field of a bounty is immutable once it is activated! It can't be edited with new submissions.

The second schema is basically all of the data representing the submission, i.e. any deliverables (files, links, etc).

Since `contactEmai`l would be required, would you imagine having `funderEmail` sometimes be the same as `contactEmail`, but sometimes different?

**Comment by jasonrhaas** [comment]
Yea, there needs to be two schemas.  One for the `bounty`, and one for the `fulfill`.

**Comment by owocki** [comment]
@jasonrhaas just synced with mark. here is where we landed for the issue schema:

```
{
  payload: {
    title: // A string representing the title of the bounty
    description: // A string representing the description of the bounty, including all requirements
    sourceFileName: // A string representing the name of the file
    sourceFileHash: // The IPFS hash of the file associated with the bounty
    sourceDirectoryHash: // The IPFS hash of the directory which can be used to access the file
    issuer: {
      // - persona schema
       name: // optional - A string representing the name of the issuer of the bounty
       email: // optional - A string representing the preferred contact email of the issuer of the bounty
       githubUsername: // optional - A string representing the github username of the issuer of the bounty
       required: // optional - A string web3 address of the issuer of the bounty
    },
    funders:[
       // array of personas (see above, issuer) of those who funded the issue.
    ],
    categories: // an array of strings, representing the categories of tasks which are being requested
    created: // the timestamp in seconds when the bounty was created
    // ------- add optional fields here -------
    webReferenceURL: // The link to the relevant repository
  }
  meta: {
    platform: // a string representing the original posting platform (ie 'gitcoin')
    schemaVersion: // a string representing the version number (ie '0.1')
    schemaName: // a string representing the name of the schema (ie 'standardSchema' or 'gitcoinSchema') 
  }
}
```
and for the fulfillment schema:
```
{
  payload: {
    description: // A string representing the description of the fulfillment, and any necessary links to works
    sourceFileName: // A string representing the name of the file being submitted
    sourceFileHash: // A string representing the IPFS hash of the file being submitted
    sourceDirectoryHash: // A string representing the IPFS hash of the directory which holds the file being submitted
    fulfiller: {
      // - persona schema
       name: // optional - A string representing the name of the issuer of the bounty
       email: // optional - A string representing the preferred contact email of the issuer of the bounty
       githubUsername: // optional - A string representing the github username of the issuer of the bounty
       required: // optional - A string web3 address of the issuer of the bounty
    },

    // ------- add optional fields here -------
  },
  meta: {
    platform: // a string representing the original posting platform (ie 'gitcoin')
    schemaVersion: // a string representing the version number (ie '0.1')
    schemaName: // a string representing the name of the schema (ie 'standardSchema' or 'gitcoinSchema')
  }
}

**Comment by jasonrhaas** [comment]
> required: // optional - A string web3 address of the issuer of the bounty

Kind of weird that the `required` field is optional.

### Bounty Schema 
- Why is there is issueURL?
- I don't think the `funders` field makes sense for the initial bounty.  For example, if someone wants to contribute more money to the contract, this field can't be changed because its immutable.
- Can I add more fields to this?  This is just the standard fields?
- Missing metadata, tokenAddress, tokenAddress, etc

### Fulfiller Schema
- Looks good

**Comment by owocki** [comment]
lol whoops.  editing to update the required / optional thing now

**Comment by owocki** [comment]
> Why is there is issueURL?

webReferenceURL -- we wanted to generalize beyond just github

> I don't think the funders field makes sense for the initial bounty. For example, if someone wants to contribute more money to the contract, this field can't be changed because its immutable.

we built this mostly to future proof the spec.  @mbeylin this is a good opint though... should there be a seperate schema for `funding` events?

> Can I add more fields to this? This is just the standard fields?

yes please do.. but please comment back (ior submit a PR back to this repo) to update the spec with the optional fields.  that way future integrations can use those same field names!

> Missing metadata, tokenAddress, tokenAddress, etc

derp.. how did we miss this? @mbeylin want to add this when you PR back to the repo?

**Comment by owocki** [comment]
just updated the `required: // optional` stuff to be `address: // required`

**Comment by owocki** [comment]
hey @mbeylin will this be updated in the standardbounties docs this week?

**Comment by jasonrhaas** [comment]
> Missing metadata, tokenAddress, tokenAddress, etc

Do we still want these fields in there?  I think we do.

**Comment by jasonrhaas** [comment]
```
    fulfiller: {
      // - persona schema
       name: // optional - A string representing the name of the issuer of the bounty
       email: // optional - A string representing the preferred contact email of the issuer of the bounty
       githubUsername: // optional - A string representing the github username of the issuer of the bounty
       address: // required - A string web3 address of the issuer of the bounty
    },
```

Assuming all these comments should be "fulfiller", not issuer.

**Comment by owocki** [comment]
> Do we still want these fields in there? I think we do. I suppose they can go under the "optional fields" category.

Yes I believe we do want them in there..  I think `tokenAddress` and `tokenName` should maybe be required fields tho.

> One other question - should the optional fields be under their own object? 
Defer to @mbeylin on this

> Assuming all these comments should be "fulfiller", not issuer.
yes

**Comment by mbeylin** [comment]
I'm amenable to including the tokenAddress, but tokenName seems a bit extra, since it can easily be gleamed by calling the contract at the tokenAddress. 

Also i think having optional fields in the same place as the main payload simplifies things. If platforms add extra fields it won't step on anyone's toes.

**Comment by mbeylin** [comment]
I'm going to change the `sourceFileName`, ` sourceFileHash`, and `sourceDirectoryHash` to be optional fields as well in the schema, seeing as not all bounties (or platforms) will have file uploads associated with them.

**Comment by mbeylin** [comment]
taken care of in https://github.com/ConsenSys/StandardBounties/pull/23

**Comment by mbeylin** [comment]
taken care of in #23
